common: &common
  adapter: postgresql
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: goals_dev

test:
  <<: *common
  database: goals_test

production:
  <<: *common
  database: goals

